### PR TITLE
Added Universal Support

### PR DESCRIPTION
**Pull request by ethan-stytch**

### CODE REVIEW

**Comment by kyle-stytch** [comment]
The Android counterpart to Apple's Universal Links is called Android App Links (https://developer.android.com/training/app-links/verify-site-associations), which do a similar thing where you put a page on your website to verify you own the site url, and then when the user taps on that link in an email, they will automatically be directed to your app without any intermediary steps.

Regular deeplinks, on the other hand, will show an intermediary dialog.

I don't think this PR is really needed to support App Links, they were exactly the same way as Deeplinks in that you need to provide a scheme and a host (however, for App Links, the scheme can only be either `http` or `https`, for regular deeplinks you. can use a custom scheme). I don't think we need to give the ability to pass in a whole URI to the SDK.

**Comment by kyle-stytch** [comment]
One other thing to note that we will want to mention in the docs: Android App Links are only supported for API Level 23 and above (our SDK supports down to API Level 21)

**Comment by ethan-stytch** [comment]
Thanks for the input @kyle-stytch. I think I'm gonna leave this PR open until we finalize how we want to approach educating clients on use of url schemes vs universal/app links. Although not necessary, this might be helpful to clients.

**Comment by kyle-stytch** [comment]
Closing in favor of https://github.com/stytchauth/stytch-android/pull/11

**Pull request closed without merging**
